version: "3"
services:
  tarantool:
    container_name: tarantool
    image: tarantool/tarantool:${TARANTOOL_VERSION}
    environment:
      TARANTOOL_PORT: 3301
    ports:
      - "3301:3301"
    volumes:
      - ${PWD}/test/box.lua:/box.lua
    command: tarantool /box.lua
