version: "3"
services:
  app:
    container_name: app
    build: .
    environment:
      TARANTOOL_HOST: tarantool
      TARANTOOL_PORT: 3301
    command: npm test
    depends_on:
      - tarantool
  tarantool:
    container_name: tarantool
    image: tarantool/tarantool:1.7
    environment:
      TARANTOOL_PORT: 3301

    volumes:
      - ${PWD}/test/box.lua:/box.lua
    command: tarantool /box.lua
